# This is a basic workflow to help you get started with Actions
name: Electron React Webpack - Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16.x]
        os:
          - windows-latest
          - macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      # Cache steps
      - name: Cache node modules
        id: node-cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Python settings
      - name: Setup Python
        uses: actions/setup-python@v4.0.0
        with:
          python-version: "3.10.6"

      # Visual Studio settings(Windows)
      - name: setup-msbuild
        if: ${{ matrix.os == 'windows-latest' }}
        uses: microsoft/setup-msbuild@v1.1

      # node-gyp Visual Studio Configuration(Windows)
      - name: setup node-gyp config
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          npm config set msvs_version 2017 --global

      # Runs a single command using the runners shell
      - name: Install Dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: |
          yarn

      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          yarn build

      - name: Prettier Format Check
        run: |
          yarn run prettier

      - name: ESLint Format Check
        run: |
          yarn run eslint

      # - name: Jest Integration Test
      #   run: |
      #     yarn test --passWithNoTests
